version: '3.1'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PW: bigoilco
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: s3cr3t
      MYSQL_DATABASE: bigoilco
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data:
